# Generated by Django 4.0.6 on 2022-07-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type_restaurant', models.CharField(max_length=100, verbose_name='Tipo de restaurante')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('phone', models.CharField(max_length=50, verbose_name='Tel{efono')),
            ],
        ),
    ]
